# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  CXX: g++-8
  CC: gcc-8

jobs:
- job: 'Linux_Build'

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: git submodule update --init --recursive
    displayName: 'Checkout submodules'

  - bash: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo add-apt-repository -y ppa:myriadrf/drivers
      sudo apt-get update
      sudo apt-get install -y libsoapysdr-dev g++-8
    displayName: 'Installing dependencies'

  - bash: |
      mkdir ./build && cd ./build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      make -j4
    displayName: 'Build'

