# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  CXX: g++-7
  CC: gcc-7

jobs:
- job: 'Linux_Build'

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: git submodule update --init --recursive
    displayName: 'Checkout submodules'

  - script: apt-get install libsoapysdr-dev
    displayName: 'Installing dependencies'

  - bash: |
      which g++-7
      mkdir ./build && cd ./build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      make -j4
    displayName: 'Build'

